/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.VariablesGlobales;
import Handlers.JPEGHandler;
import Handlers.JPEGImageCopy;
import Handlers.JPEGImageHandlerBN;
import Handlers.JPEGImageHandlerColors;
import Handlers.JPEGImageHandlerRotator;
import Handlers.JPEGtoBMPImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Javier
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Editor");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUrl = new javax.swing.JLabel();
        btnImagenSeleccionar = new javax.swing.JButton();
        rbConvertir = new javax.swing.JRadioButton();
        rbCopia = new javax.swing.JRadioButton();
        rbRVAS = new javax.swing.JRadioButton();
        rbModificarImagen = new javax.swing.JRadioButton();
        rbBN = new javax.swing.JRadioButton();
        btnEjecutar = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 83, 131));

        lbUrl.setForeground(new java.awt.Color(255, 255, 255));
        lbUrl.setText("URL");

        btnImagenSeleccionar.setText("Seleccionar Imagen");
        btnImagenSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenSeleccionarActionPerformed(evt);
            }
        });

        rbConvertir.setBackground(new java.awt.Color(28, 83, 131));
        rbConvertir.setForeground(new java.awt.Color(255, 255, 255));
        rbConvertir.setText("JPEG a BMP y viceversa");
        rbConvertir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rbCopia.setBackground(new java.awt.Color(28, 83, 131));
        rbCopia.setForeground(new java.awt.Color(255, 255, 255));
        rbCopia.setText("copia a JPEG");
        rbCopia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rbRVAS.setBackground(new java.awt.Color(28, 83, 131));
        rbRVAS.setForeground(new java.awt.Color(255, 255, 255));
        rbRVAS.setText("Rojo Verde Azul Sepia");
        rbRVAS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbRVAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRVASActionPerformed(evt);
            }
        });

        rbModificarImagen.setBackground(new java.awt.Color(28, 83, 131));
        rbModificarImagen.setForeground(new java.awt.Color(255, 255, 255));
        rbModificarImagen.setText("Modifcar Imagen");
        rbModificarImagen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rbBN.setBackground(new java.awt.Color(28, 83, 131));
        rbBN.setForeground(new java.awt.Color(255, 255, 255));
        rbBN.setText("Blanco y negro");
        rbBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBNActionPerformed(evt);
            }
        });

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImagenSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(rbCopia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbRVAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbModificarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUrl)
                    .addComponent(btnImagenSeleccionar))
                .addGap(43, 43, 43)
                .addComponent(rbConvertir)
                .addGap(18, 18, 18)
                .addComponent(rbCopia)
                .addGap(18, 18, 18)
                .addComponent(rbRVAS)
                .addGap(18, 18, 18)
                .addComponent(rbModificarImagen)
                .addGap(18, 18, 18)
                .addComponent(rbBN)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalir))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRVASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRVASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRVASActionPerformed

    private void rbBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBNActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntSalirActionPerformed

    private void btnImagenSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenSeleccionarActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione una imagen");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos de imagen","jpg","bmp"));

        int resultado = chooser.showOpenDialog(this);

        if(resultado == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String fileName = selectedFile.getName(); 
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            lbUrl.setText(imageIcon.toString());    
            VariablesGlobales.imgRuta = imageIcon.toString();
        }

    }//GEN-LAST:event_btnImagenSeleccionarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        if(VariablesGlobales.imgRuta == null) {
            JOptionPane.showMessageDialog(null,"Seleccione una imagen antes de ejecutar el editro");
        }
        else {
            if(rbConvertir.isSelected()){
                JPEGtoBMPImage handlerBN = new JPEGtoBMPImage(VariablesGlobales.imgRuta.replace("\\", "/"));
                try{
                    JPEGHandler.runHandler(handlerBN);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            if(rbCopia.isSelected()){
                JPEGImageCopy handlerBN = new JPEGImageCopy(VariablesGlobales.imgRuta.replace("\\", "/"));
                try{
                    JPEGHandler.runHandler(handlerBN);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            if(rbRVAS.isSelected()){
                JPEGImageHandlerColors handlerBN = new JPEGImageHandlerColors(VariablesGlobales.imgRuta.replace("\\", "/"));
                try{
                    JPEGHandler.runHandler(handlerBN);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            if(rbModificarImagen.isSelected()){
                JPEGImageHandlerRotator handlerBN = new JPEGImageHandlerRotator(VariablesGlobales.imgRuta.replace("\\", "/"));
                try{
                    JPEGHandler.runHandler(handlerBN);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            if(rbBN.isSelected()){
                JPEGImageHandlerBN handlerBN = new JPEGImageHandlerBN(VariablesGlobales.imgRuta.replace("\\", "/"));
                try{
                    JPEGHandler.runHandler(handlerBN);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
        
    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnImagenSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbUrl;
    private javax.swing.JRadioButton rbBN;
    private javax.swing.JRadioButton rbConvertir;
    private javax.swing.JRadioButton rbCopia;
    private javax.swing.JRadioButton rbModificarImagen;
    private javax.swing.JRadioButton rbRVAS;
    // End of variables declaration//GEN-END:variables
}
